# Generated by Django 3.0.3 on 2022-02-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='creator',
            new_name='groupCreator',
        ),
    ]
