# Generated by Django 3.0.3 on 2022-02-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0004_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
