# Generated by Django 3.0.3 on 2022-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0006_auto_20220213_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
