# Generated by Django 3.0.3 on 2022-02-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0008_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
