# Generated by Django 3.0.3 on 2022-02-14 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snapp', '0013_auto_20220214_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
