# Generated by Django 3.0.3 on 2022-02-14 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snapp', '0014_auto_20220214_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
