# Generated by Django 3.0.3 on 2022-02-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0016_auto_20220214_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='owner',
        ),
    ]
