# Generated by Django 3.0.3 on 2022-02-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0017_remove_galleryimage_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
