# Generated by Django 3.0.3 on 2022-02-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0025_auto_20220222_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='friends',
        ),
    ]
