# Generated by Django 3.0.3 on 2022-02-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0032_auto_20220224_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='user',
            new_name='owner',
        ),
    ]
